/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';

 
const Test11 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `446px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Ellipse1 = styled("img")({  
  width: "20vw",  
  position: `absolute`,  
  left: `23px`,  
  top: `25px`,  
});
  
const HelloWorld = styled("img")({  
  width: "90px",  
  position: `absolute`,  
  left: `421px`,  
  top: `42px`,  
});
  
const Rectangle1 = styled("img")({  
  height: `119px`,  
  width: `119px`,  
  position: `absolute`,  
  left: `266px`,  
  top: `223px`,  
});
 
function Test1(props) {
  return (
    <Test11  className={props.className}   >
      <Ellipse1  src={`assets/images/test1_Ellipse_1.svg`} alt={"Ellipse 1"}/>
      <HelloWorld  src={`assets/images/test1_HELLO_WORLD.svg`} alt={"HELLO WORLD"}/>
      <Rectangle1  src={`assets/images/test1_Rectangle_1.png`} alt={"Rectangle 1"}/>
    </Test11>
  );
}

export default Test1;
