/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Ellipse1Image from 'src/assets/images/test1_Ellipse_1.svg';
import HelloWorldImage from 'src/assets/images/test1_HELLO_WORLD.svg';
import Rectangle1Image from 'src/assets/images/test1_Rectangle_1.png';
import { styled } from '@mui/material/styles';
import { Test1Props } from 'src/types';

 
const Test11: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `446px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Ellipse1: any = styled("img")({  
  height: `auto`,  
  width: "234px",  
  position: `absolute`,  
  left: `23px`,  
  top: `25px`,  
});
  
const HelloWorld: any = styled("img")({  
  height: `auto`,  
  width: "90px",  
  position: `absolute`,  
  left: `421px`,  
  top: `42px`,  
});
  
const Rectangle1: any = styled("img")({  
  height: `119px`,  
  width: `119px`,  
  position: `absolute`,  
  left: `266px`,  
  top: `223px`,  
});
 
function Test1(props: Test1Props): JSX.Element {
  return (
    <Test11  className={props.className}   >
      <Ellipse1  src={Ellipse1Image} alt={"Ellipse 1"}/>
      <HelloWorld  src={HelloWorldImage} alt={"HELLO WORLD"}/>
      <Rectangle1  src={Rectangle1Image} alt={"Rectangle 1"}/>
    </Test11>
  );
}

export default Test1;
