/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import ProductCard1 from 'components/ProductCard1/ProductCard1';
import { Repeat3Props } from 'types';
import { animated, useSpring, easings } from 'react-spring';
import useRepeat3 from 'components/Repeat3/useRepeat3';
 
const Repeat31: any = styled("div")({  
  display: `grid`,  
  position: `relative`,  
  isolation: `isolate`,  
  width: "100%",  
  padding: `50px`,  
  boxSizing: `border-box`,  
  height: `auto`,  
  gridTemplateColumns: `repeat(auto-fit, minmax(417px, 1fr))`,  
  columnGap: `40px`,  
  rowGap: `40px`,  
});
  
const ProductCard11: any = styled(ProductCard1)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
}));
 
function Repeat3(props: Repeat3Props): JSX.Element {
  
  const {data, fns} = useRepeat3();
    return (
    <Repeat31  className={props.className}   >
      {undefined && undefined.map((undefined: any, index: number) => {
        return (
          (fns.onVisible(prop.data)) &&
            <ProductCard11  key={index}  onClick={() => {  101794386107989Api.start({ ...{"opacity":0}, delay: 0 });  }} />
        );
      })}
    </Repeat31>
  );
}

export default Repeat3;
