/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useRepeat3 = () => {
  let data: any = {};
  const onVisible = (): void => {
    console.log('fff')
  };
   const onVisible = (): void => {};

  let fns: {onVisible: () => void} = {onVisible};
  return {data, fns};
}

export default useRepeat3;
