/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { Frame1Props } from 'types';
import useFrame1 from 'components/Frame1/useFrame1';
 
const Frame11: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Dfgdfgdfgdf: any = styled("div", {
    shouldForwardProp: prop => !["data"].includes(prop.toString())
    })(({ data }: any) =>({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: data.color,  
  fontStyle: `normal`,  
  fontFamily: `Oswald`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `608px`,  
  top: `336px`,  
}));
 
function Frame1(props: Frame1Props): JSX.Element {
  
  const {data} = useFrame1();
    return (
    <Frame11  className={props.className}   >
      <Dfgdfgdfgdf data={data} >
        {`dfgdfgdfgdf`}
          </Dfgdfgdfgdf>
    </Frame11>
  );
}

export default Frame1;
