/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import { Frame4Props } from 'types';

 
const Frame41: any = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: `714px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Image2: any = styled("img")({  
  height: `314px`,  
  width: `490px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `0px`,  
  top: `125px`,  
});
  
const Image21: any = styled("img")({  
  height: `143px`,  
  width: `284px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `718px`,  
  top: `274px`,  
});
 
function Frame4(props: Frame4Props): JSX.Element {
  
  return (
    <Frame41  className={props.className}   >
      <Image2  src={`assets/images/Frame4_image_2_1.png`} alt={"image 2"}/>
      <Image21  src={`assets/images/Frame4_image_2.png`} alt={"image 2"}/>
    </Frame41>
  );
}

export default Frame4;
